# Redis 配置
redis:
  defalut:
    port: 6379
    host: localhost
    username: default
    password: Aa@123456
    db: 0

# Mysql 配置
datasource:
  defalut:
    type: mysql
    port: 3306
    host: localhost
    username: root
    password: Aa@123456
    database: vivy-nest-admin
    synchronize: true
    autoLoadEntities: true
    bigNumberStrings: false
    supportBigNumbers: true

# Bull 配置
bull:
  redis:
    port: 6379
    host: localhost
    username: default
    password: Aa@123456
    db: 1
