// Do not manually change, generated by @vivy-common/mybatis
// @ts-nocheck
/* eslint-disable */
/* prettier-ignore */
declare module '@vivy-common/mybatis' {
  interface MybatisMapper {
    'gen.gen.mapper': 'selectDbTableList' | 'selectDbTableListByNames' | 'selectDbTableColumnsByName'
  }
}

export {}
