export const SECURITY_OPTIONS = Symbol('SECURITY_OPTIONS')
export const PUBLIC_METADATA = 'PUBLIC_METADATA'
export const INNER_AUTH_METADATA = 'INNER_AUTH_METADATA'
export const REQUIRE_ROLES_METADATA = 'REQUIRE_ROLES_METADATA'
export const REQUIRE_PERMISSIONS_METADATA = 'REQUIRE_PERMISSIONS_METADATA'
